!!
------------------------------------------------------------------------
THIS IS A PROGRAM TO TEST THE LEXICAL GRAMMAR OF MINI-PASCAL.
------------------------------------------------------------------------
PROJECT TITLE: LEXICAL TESTER
PURPOSE OF PROJECT: 
VERSION or DATE: 16/03/2019
HOW TO START THIS PROJECT:  
AUTHORS:    GUSTAVO MARQUES ( @GUTODISSE )
USER INSTRUCTIONS: 
!
    Num1 := 1;  ! TEST COMMENT
    Num3 := 1.1;
    Num3 := .1;
    testes := true;

